name: Build server and run linter
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Client build
      - name: Setup Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update OS
        run: sh ./scripts/before_install.sh
        
