name: Build server
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring env
        id: setpullrequest
        run: |
          PULL_REQUEST=$(cat $GITHUB_EVENT_PATH | jq -r ".pull_request.number")
          if [[ "$PULL_REQUEST" = "null" ]]; then PULL_REQUEST="false"; fi
          echo "PULL_REQUEST=$PULL_REQUEST" >> $GITHUB_ENV
          echo "BRANCH=${{env.GITHUB_REF}}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{env.GITHUB.RUN_NUMBER}}" >> $GITHUB_ENV
      # Client build
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          bash -e ./scripts/before_install.sh
          bash -e ./scripts/build.sh
      
      - name: cleanup
        run: bash -e ./scripts/cleanup.sh
      
      - name: cleanup on failure
        if: ${{ failure() }}
        run: bash -e ./scripts/cleanup.sh
        
