name: Build server
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Client build
      - name: setup Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Install nvm
        shell: bash -l {0}
        run: |
          cd ..
          echo $HOME
          export NVM_DIR="$HOME/.nvm"
          mkdir $NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
          echo "source $NVM_DIR/nvm.sh --install" >> "$HOME/.bash_profile"
          cd -
          source $HOME/.bash_profile
          nvm install

      - name: ci
        run: |
          bash -e ./scripts/before_install.sh
          bash -e ./scripts/build.sh
      
      - name: cleanup
        run: bash -e ./scripts/cleanup.sh
      
      - name: cleanup on failure
        if: ${{ failure() }}
        run: bash -e ./scripts/cleanup.sh
        
